# This is a basic workflow to help you get started with Actions

name: Linting

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install nox_poetry
    - name: Assess code quality
      run: nox -s style_checking
    - name: Assess package quality
      run: nox -s pyroma
    - name: Type checking
      run: nox -s type_checking

  doc_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install nox_poetry
        poetry install -v
    - name: Check if docs build
      run: |
        nox -s build_doc
