# This is a basic workflow to help you get started with Actions

name: Linting

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install black
        poetry install -v
    - name: Check black code style
      run: black --config pyproject.toml --diff forayer/ tests/
    - name: Assess code quality
      run: poetry run pflake8 forayer/ tests/
  doc_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install -v
    - name: Check doc quality
      run: poetry run pflake8 --select "DAR,D102,103" --ignore "DAR103" forayer/
