# This is a basic workflow to help you get started with Actions

name: Code quality

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install black
        python -m pip install pep8-naming
        python -m pip install pyflakes
        python -m pip install flake8-bugbear
        python -m pip install flake8-simplify
        python -m pip install pyproject-flake8
        python -m pip install tox
    - name: Check black code style
      run: black --config pyproject.toml --diff forayer/ tests/
    - name: Assess code quality
      run: poetry run pflake8 forayer/ tests/
    - name: Check doc quality
      run: poetry run pflake8 --select D forayer/
