# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install tox
    - name: Test with tox
      run: tox | tee report.txt
    - name: Create test coverage badge when on master and not on pull request
      run: |
        echo "cov=$(grep 'TOTAL' report.txt | tail -1 | sed 's/\s\+/,/g' | cut -d',' -f 4 | sed 's/%//g' )" >> $GITHUB_ENV
        rm report.txt
    - name: Get badge color red
      if: ${{ env.cov < 51 }}
      run: |
        echo "cov_color=red" >> $GITHUB_ENV
    - name: Get badge color orange
      if: ${{ env.cov < 71 && env.cov > 50}}
      run: |
        echo "cov_color=orange" >> $GITHUB_ENV
    - name: Get badge color yellow
      if: ${{ env.cov < 81 && env.cov > 70}}
      run: |
        echo "cov_color=yellow" >> $GITHUB_ENV
    - name: Get badge color yellowgreen
      if: ${{ env.cov < 86 && env.cov > 80}}
      run: |
        echo "cov_color=yellowgreen" >> $GITHUB_ENV
    - name: Get badge color green
      if: ${{ env.cov < 95 && env.cov > 85}}
      run: |
        echo "cov_color=green" >> $GITHUB_ENV
    - name: Get badge color brightgreen
      if: ${{ env.cov > 94}}
      run: |
        echo "cov_color=brightgreen" >> $GITHUB_ENV
    - name: Create test badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 6d07d95e43929bcbf9d031c2c8f2015f
        filename: forayer_test_gist.json
        label: coverage
        message: ${{ env.cov }} %
        color: ${{ env.cov_color }}
